import { contextBridge, ipcRenderer } from 'electron';
import type { AssistantAnchor, DesktopAPI, UpdaterStatus } from '../shared/contracts';
const api: DesktopAPI = {
  state: () => ipcRenderer.invoke('state'), create: task => ipcRenderer.invoke('create', task),
  update: (id, patch, revision) => ipcRenderer.invoke('update', id, patch, revision),
  remove: (id, revision) => ipcRenderer.invoke('remove', id, revision), restore: id => ipcRenderer.invoke('restore', id),
  snooze: id => ipcRenderer.invoke('snooze', id),
  createCategory: category => ipcRenderer.invoke('category:create', category),
  updateCategory: (id, category, revision) => ipcRenderer.invoke('category:update', id, category, revision),
  removeCategory: (id, revision) => ipcRenderer.invoke('category:remove', id, revision),
  window: (action, animate) => ipcRenderer.invoke('window', action, animate),
  windowWidth: (width, animate) => ipcRenderer.invoke('window:width', width, animate),
  compactHeight: height => ipcRenderer.invoke('compact:height', height),
  dockEnabled: enabled => ipcRenderer.invoke('dockEnabled', enabled),
  dockHover: open => ipcRenderer.invoke('dockHover', open),
  dockMove: point => ipcRenderer.invoke('dockMove', point),
  dockIcon: (action, preset) => ipcRenderer.invoke('dockIcon', action, preset),
  assistant: input => ipcRenderer.invoke('assistant', input), assistantReady: () => ipcRenderer.invoke('assistant:ready'),
  openSettings: animate => ipcRenderer.invoke('settings:open', animate),
  settings: input => ipcRenderer.invoke('settings', input),
  saveProvider: input => ipcRenderer.invoke('provider:save', input),
  removeProvider: id => ipcRenderer.invoke('provider:remove', id),
  saveModel: input => ipcRenderer.invoke('model:save', input),
  removeModel: id => ipcRenderer.invoke('model:remove', id),
  setModelVision: input => ipcRenderer.invoke('model:vision', input),
  testConnection: input => ipcRenderer.invoke('provider:test', input),
  saveRlcdProvider: input => ipcRenderer.invoke('rlcd:provider:save', input),
  removeRlcdProvider: id => ipcRenderer.invoke('rlcd:provider:remove', id),
  saveRlcdModel: input => ipcRenderer.invoke('rlcd:model:save', input),
  removeRlcdModel: id => ipcRenderer.invoke('rlcd:model:remove', id),
  testRlcdConnection: input => ipcRenderer.invoke('rlcd:provider:test', input),
  activateProfile: id => ipcRenderer.invoke('profile:activate', id),
  ask: input => ipcRenderer.invoke('ask', input),
  chatList: () => ipcRenderer.invoke('chat:list'),
  chatOpen: id => ipcRenderer.invoke('chat:open', id),
  chatNew: () => ipcRenderer.invoke('chat:new'),
  chatRemove: id => ipcRenderer.invoke('chat:remove', id),
  chatDraft: (id, text) => ipcRenderer.invoke('chat:draft', id, text),
  chatAsk: input => ipcRenderer.invoke('chat:ask', input),
  onChatUpdate: callback => { const listener = (_event: Electron.IpcRendererEvent, session: import('../shared/contracts').ChatSession) => callback(session); ipcRenderer.on('chat:update', listener); return () => ipcRenderer.removeListener('chat:update', listener); },
  onChatSelected: callback => { const listener = (_event: Electron.IpcRendererEvent, session: import('../shared/contracts').ChatSession) => callback(session); ipcRenderer.on('chat:selected', listener); return () => ipcRenderer.removeListener('chat:selected', listener); },
  updateProposal: input => ipcRenderer.invoke('proposal:update', input),
  apply: input => ipcRenderer.invoke('apply', input), cancelAI: () => ipcRenderer.invoke('cancelAI'),
  review: () => ipcRenderer.invoke('review'), exportData: () => ipcRenderer.invoke('exportData'),
  openData: () => ipcRenderer.invoke('openData'),
  updaterStatus: () => ipcRenderer.invoke('updater:status'),
  updaterCheck: () => ipcRenderer.invoke('updater:check'),
  updaterInstall: () => ipcRenderer.invoke('updater:install'),
  openUpdateLog: (tag?: string) => ipcRenderer.invoke('updater:openLog', tag),
  onAskDelta: callback => { const listener = (_event: Electron.IpcRendererEvent, text: string) => callback(text); ipcRenderer.on('ai:delta', listener); return () => ipcRenderer.removeListener('ai:delta', listener); },
  onChanged: callback => { const listener = () => callback(); ipcRenderer.on('changed', listener); return () => ipcRenderer.removeListener('changed', listener); },
  onAssistantVisibility: callback => { const listener = (_event: Electron.IpcRendererEvent, visible: boolean) => callback(visible); ipcRenderer.on('assistant:visibility', listener); return () => ipcRenderer.removeListener('assistant:visibility', listener); },
  onAssistantPrompt: callback => { const listener = (_event: Electron.IpcRendererEvent, prompt: string) => callback(prompt); ipcRenderer.on('assistant:prompt', listener); return () => ipcRenderer.removeListener('assistant:prompt', listener); },
  onAssistantAnchor: callback => { const listener = (_event: Electron.IpcRendererEvent, anchor: AssistantAnchor) => callback(anchor); ipcRenderer.on('assistant:anchor', listener); return () => ipcRenderer.removeListener('assistant:anchor', listener); },
  onOpenSettings: callback => { const listener = () => callback(); ipcRenderer.on('settings:open', listener); return () => ipcRenderer.removeListener('settings:open', listener); },
  onUpdater: callback => { const listener = (_event: Electron.IpcRendererEvent, status: UpdaterStatus) => callback(status); ipcRenderer.on('updater:status', listener); return () => ipcRenderer.removeListener('updater:status', listener); },
};
contextBridge.exposeInMainWorld('desktop', api);
